### ISSUE TITLE
Allow manual setting current_exe in self_delete function

### ISSUE THREAD

**Issue by bschoenmaeckers** [mitsuhiko/self-replace#20]
I need to set a custom exe path because I'm moving the current executable during my own update process on windows. And so to schedule proper deletion of the old executable env::current_exe is not correct anymore.

```rust
let orig = current_exe()?;
let temp = orig.with_extension("old");
fs::rename(&orig, &temp)?;

if do_update().is_ok() {
  self_replace::self_delete()?;  // This will not work because current_exe does not point to correct file anymore.
  // self_replace::self_delete(&temp)?;  // This could be a solution 
} else {
  fs::rename(&temp, &orig)?;
}

```

**Comment by bschoenmaeckers** [comment]
Making self_replace::windows::schedule_self_deletion_on_shutdown public can also be an option.

**Comment by mitsuhiko** [comment]
I would be curious to learn why you are moving the exe to a temporary location. Can you share that? The challenge with deleting "another exe" is that that needs to be executable too. So in this case the deletion can't work because `orig.with_extension("old");` makes it non executable on windows as such deletion is impossible.

Would be good to understand your exact workflow so this might be better supported.

**Comment by bschoenmaeckers** [comment]
The name of the temp file is not relevant so it could be `old.exe` or something else. The rename is only done so the update process can create a new executable in the original location.

**Comment by mitsuhiko** [comment]
> The rename is only done so the update process can create a new executable in the original location.

Can you share why this is necessary?  Is the updater unable to place the file at a temporary location and then move it over?  Because that's the intended way in which this works.

**Comment by mitsuhiko** [comment]
Closing this due to lack of feedback.
